// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCSVN7vHyGSOtl1145dZ4CVX3onMrTts',
    appId: '1:278105376443:web:0910a1a9f5eb20c507cb9e',
    messagingSenderId: '278105376443',
    projectId: 'movie-app-8558e',
    authDomain: 'movie-app-8558e.firebaseapp.com',
    storageBucket: 'movie-app-8558e.firebasestorage.app',
    measurementId: 'G-XYQ6C5GP45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdkXAgmU5tuOCJe_AwgDqQpje0tVgYiU',
    appId: '1:278105376443:android:afbb2ca6b6858f4707cb9e',
    messagingSenderId: '278105376443',
    projectId: 'movie-app-8558e',
    storageBucket: 'movie-app-8558e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw2TGbi3klR80tjzF96e-qh2qV2oNW_XY',
    appId: '1:278105376443:ios:f2fd5b584a16ea5007cb9e',
    messagingSenderId: '278105376443',
    projectId: 'movie-app-8558e',
    storageBucket: 'movie-app-8558e.firebasestorage.app',
    iosBundleId: 'com.example.movieAppNewDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw2TGbi3klR80tjzF96e-qh2qV2oNW_XY',
    appId: '1:278105376443:ios:f2fd5b584a16ea5007cb9e',
    messagingSenderId: '278105376443',
    projectId: 'movie-app-8558e',
    storageBucket: 'movie-app-8558e.firebasestorage.app',
    iosBundleId: 'com.example.movieAppNewDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuCSVN7vHyGSOtl1145dZ4CVX3onMrTts',
    appId: '1:278105376443:web:6b00c9187e49e53407cb9e',
    messagingSenderId: '278105376443',
    projectId: 'movie-app-8558e',
    authDomain: 'movie-app-8558e.firebaseapp.com',
    storageBucket: 'movie-app-8558e.firebasestorage.app',
    measurementId: 'G-2ZGY9759VD',
  );
}
